#*Plan* 
- ## NumPy
- ## Pandas

In [74]:
from IPython.display import Image
from IPython.core.display import HTML 

In [77]:
Image(url= "https://miro.medium.com/max/765/1*qePzd2m_uIPvsozXYh89CQ.png")


Numpy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.<br>
One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. There are a number of reasons for this, most important NumPy operations perform complex computations on entire arrays without the need for Python loops. <br>

NumPy most important object is n-dimensional array or ndarray.

Numpy is 

1.   Convinient
2.   Fast
3.   Memory efficient



Numpy is convinient

In [2]:
import numpy as np

In [67]:
l1 = [100,200,300,400,500]
l2 = [100,100,100,100,100]
l3 = []
for priv, soc in zip(l1,l2):
  l3.append(priv+soc)
print(l3)

[200, 300, 400, 500, 600]


In [68]:
a1 = np.array([100,200,300,400,500])
a2 = np.array([100,100,100,100,100])

In [70]:
a3 = a1+a2
a3

array([200, 300, 400, 500, 600])

In [15]:
a1/a2

array([1., 2., 3., 4., 5.])

In [71]:
a1*a2

array([10000, 20000, 30000, 40000, 50000])

In [72]:
a1-a2

array([  0, 100, 200, 300, 400])

Numpy is Fast <br>
To give you an idea of perfomance difference, consider a NumPy array of one million integers, and the equivalent Python list.


In [7]:
my_arr = np.arange(100000000)

In [8]:
my_list = list(range(100000000))

In [9]:
%time my_arr2 = my_arr*2

CPU times: user 141 ms, sys: 347 ms, total: 487 ms
Wall time: 494 ms


In [11]:
%time my_arr2 = []
for item in my_list:
  my_arr2.append(item*2)


CPU times: user 835 ms, sys: 130 ms, total: 966 ms
Wall time: 968 ms


Memory efficient

In [18]:
import sys

In [20]:
ls = range(100)
arr = np.arange(100)
print(sys.getsizeof(1)*len(ls))
print(arr.size*arr.itemsize)

2800
800


A ndarray is a generic multidimensional container for homogenous data; that is all of the elements must be the same type. Every array has a shape, a tuple indicating the size of the each dimension, and a dtype, an object describing the data type of the array:

In [21]:
data = np.random.randn(2,3)

In [22]:
data

array([[-1.61546722, -1.02653239,  0.6399928 ],
       [-0.56456418,  0.11410426, -1.2384171 ]])

In [23]:
data*10

array([[-16.15467225, -10.26532392,   6.39992805],
       [ -5.64564183,   1.14104259, -12.38417095]])

In [25]:
data.shape

(2, 3)

In [26]:
data.dtype

dtype('float64')

In [27]:
data1 = [6, 7.5, 8 ,0 ,1 ]

In [28]:
arr1 = np.array(data1)

In [29]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [30]:
data2 = [[1,2,3,4], [2,3,4,4]]
arr2 = np.array(data2)

In [31]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 4]])

In [32]:
arr2.shape

(2, 4)

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Basic Indexing and Slicing
NumPy arrat indexing is arich topic, as there are many ways you may want to select a subset of your data or individual elements. On-dimensional arrays are simple; they act similarly to Python lists

In [37]:
a = np.arange(10)
a[0]

0

In [39]:
a[3:9]

array([3, 4, 5, 6, 7, 8])

In [40]:
a[3:9] = 999
a

array([  0,   1,   2, 999, 999, 999, 999, 999, 999,   9])

Higher dimensional case

In [42]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1]

array([4, 5, 6])

In [44]:
arr2d[1][1]

5

In [45]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
data = np.random.randn(7,4)

In [48]:
data

array([[ 0.09489228,  0.25227448,  0.9420906 , -0.11185268],
       [ 1.75817408,  0.24827457, -1.0893095 ,  0.11184248],
       [-1.48730443,  0.06103998,  1.36347826, -0.36845844],
       [-0.58380157, -2.68177921, -0.32324019,  0.88857594],
       [ 0.12173626,  0.3285586 , -0.86666293,  0.38948386],
       [ 1.75059663, -1.98075485,  0.39540382, -0.12031955],
       [ 1.08685414,  0.41581627,  0.31100378, -0.92119794]])

In [50]:
data[data < 0] = 0

In [51]:
data

array([[0.09489228, 0.25227448, 0.9420906 , 0.        ],
       [1.75817408, 0.24827457, 0.        , 0.11184248],
       [0.        , 0.06103998, 1.36347826, 0.        ],
       [0.        , 0.        , 0.        , 0.88857594],
       [0.12173626, 0.3285586 , 0.        , 0.38948386],
       [1.75059663, 0.        , 0.39540382, 0.        ],
       [1.08685414, 0.41581627, 0.31100378, 0.        ]])

### Statistical function

In [54]:
arr = np.random.randn(5,4)

In [56]:
arr

array([[-0.27435423,  0.07262001,  0.85731941,  0.36064605],
       [ 1.17338914, -0.3785971 , -0.0276085 , -0.51663422],
       [-0.79517686,  0.36080684,  0.09959116, -0.08265027],
       [ 0.62033476,  2.14710506,  0.14869197, -0.98228391],
       [-1.06439914,  0.18658554, -0.8141048 ,  1.32160877]])

In [57]:
arr.mean()

0.12064448444455902

In [58]:
np.mean(arr)

0.12064448444455902

In [59]:
# across columns
arr.mean(axis=1)

array([ 0.25405781,  0.06263733, -0.10435728,  0.48346197, -0.09257741])

In [60]:
#across rows
arr.mean(axis = 0)

array([-0.06804127,  0.47770407,  0.05277785,  0.02013728])

In [61]:
arr.sum()

2.4128896888911804

In [62]:
data

array([[0.09489228, 0.25227448, 0.9420906 , 0.        ],
       [1.75817408, 0.24827457, 0.        , 0.11184248],
       [0.        , 0.06103998, 1.36347826, 0.        ],
       [0.        , 0.        , 0.        , 0.88857594],
       [0.12173626, 0.3285586 , 0.        , 0.38948386],
       [1.75059663, 0.        , 0.39540382, 0.        ],
       [1.08685414, 0.41581627, 0.31100378, 0.        ]])

In [64]:
data.sort()
data

array([[0.        , 0.09489228, 0.25227448, 0.9420906 ],
       [0.        , 0.11184248, 0.24827457, 1.75817408],
       [0.        , 0.        , 0.06103998, 1.36347826],
       [0.        , 0.        , 0.        , 0.88857594],
       [0.        , 0.12173626, 0.3285586 , 0.38948386],
       [0.        , 0.        , 0.39540382, 1.75059663],
       [0.        , 0.31100378, 0.41581627, 1.08685414]])

In [66]:
data.sort(axis = 0)
data

array([[0.        , 0.        , 0.        , 0.38948386],
       [0.        , 0.        , 0.06103998, 0.88857594],
       [0.        , 0.        , 0.24827457, 0.9420906 ],
       [0.        , 0.09489228, 0.25227448, 1.08685414],
       [0.        , 0.11184248, 0.3285586 , 1.36347826],
       [0.        , 0.12173626, 0.39540382, 1.75059663],
       [0.        , 0.31100378, 0.41581627, 1.75817408]])

In [79]:
Image(url = "https://miro.medium.com/max/819/1*Dss7A8Z-M4x8LD9ccgw7pQ.png")

# Pandas 
Pandas contains data structures and data manipulation tools designed to make data cleaning
and analysis fast and easy in Python. <br> 
Pandas is often used in tandem with numerical
computing tools like NumPy and SciPy, analytical libraries like statsmodels and
scikit-learn, and data visualization libraries like matplotlib. <br> Pandas adopts significant
parts of NumPy’s idiomatic style of array-based computing, especially array-based
functions and a preference for data processing without for loops

### Series and DataFrames

In [2]:
import pandas as pd

In [82]:
obj = pd.Series([4, 7,-5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [85]:
Image(url = "https://embed-fastly.wistia.com/deliveries/dac3116985e248b4ececd79427d2c332a3a6dd16.webp?image_crop_resized=1280x800")

In [4]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [5]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

-5

In [8]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [9]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In a way, you can think of Series as Python dictionary.

In [10]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

In [11]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [13]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [14]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

## DataFrame
A DataFrame represents a rectangular table of data and contains an ordered collec‐
tion of columns, each of which can be a different value type (numeric, string,
boolean, etc.). The DataFrame has both a row and column index; it can be thought of
as a dict of Series all sharing the same index

In [20]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [21]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [22]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [23]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
index=['one', 'two', 'three', 'four', 'five', 'six'])

In [24]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [28]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [29]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [33]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [36]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three', 'four'])

In [37]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [38]:
data.drop(['one', 'two'], axis = 'columns')

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [39]:
data.drop(['Ohio','Colorado'], axis = 'rows')

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15